name: 'Helm chart version bumper'
description: 'Bumps the version of a helm chart with pythons bump2version. Based on the last commit messages inside the helm chart directory'
inputs:
  chart:
    description: 'The chart to update. Must reside inside the charts subdirectory.'
    required: true
#    TODO also allow passing of chart dir location
outputs:
  changes:
    description: Is 'true' if the action made changes, 'false' otherwise.
  new_version:
    description: New version number as result of bump2version run
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHART_NAME: ${{ inputs.chart }}
