name: Release charts
on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'charts/**'
  schedule:
    # every friday at 4 o'clock
    - cron: '0 16 * * 5'
  workflow_dispatch:
jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Bump Keycloak
      id: bump_keycloak
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: keycloak

    - name: Update Keycloak Changelog
      run: ./github/scripts/generate-changelog.sh
      env:
        CHART_NAME: keycloak
        NEW_VERSION: steps.bump_keycloak.outputs.new_version
      if: steps.bump_keycloak.outputs.changes == "true" 
  
    - name: Bump Keycloak.X
      id: bump_keycloakx
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: keycloakx
  
    - name: Update Keycloak.X Changelog
      run: ./github/scripts/generate-changelog.sh
      env:
        CHART_NAME: keycloakx
        NEW_VERSION: steps.bump_keycloakx.outputs.new_version
      if: steps.bump_keycloakx.outputs.changes == "true" 
  
    - name: Bump Mailhog
      id: bump_mailhog
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: mailhog

    - name: Update Mailhog Changelog
      run: ./github/scripts/generate-changelog.sh
      env:
        CHART_NAME: mailhog
        NEW_VERSION: steps.bump_mailhog.outputs.new_version
      if: steps.bump_mailhog.outputs.changes == "true" 

    - name: Push Results
      id: pushResults
      run: |
        if git merge-base --is-ancestor HEAD @{u} ; then
          echo '::set-output name=publish::false'
          echo "No push necesarry"
        else
          echo "Version bumps happened. Pushing now..."
          git push
          echo '::set-output name=publish::true'
        fi
    outputs:
      publish: ${{ steps.pushResults.outputs.publish }}

  upload:
    runs-on: ubuntu-latest
    needs:
      - bump-versions
    if: needs.bump-versions.outputs.publish == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

